# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Giuliano/Desktop/BRAMtoVGA/BRAMtoVGA.srcs/sources_1/bd/BRAMRW/ip/BRAMRW_blk_mem_gen_0_0/BRAMRW_blk_mem_gen_0_0.xci
# IP: The module: 'BRAMRW_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Giuliano/Desktop/BRAMtoVGA/BRAMtoVGA.srcs/sources_1/bd/BRAMRW/ip/BRAMRW_blk_mem_gen_0_0/BRAMRW_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAMRW_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Giuliano/Desktop/BRAMtoVGA/BRAMtoVGA.srcs/sources_1/bd/BRAMRW/ip/BRAMRW_blk_mem_gen_0_0/BRAMRW_blk_mem_gen_0_0.xci
# IP: The module: 'BRAMRW_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Giuliano/Desktop/BRAMtoVGA/BRAMtoVGA.srcs/sources_1/bd/BRAMRW/ip/BRAMRW_blk_mem_gen_0_0/BRAMRW_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAMRW_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
