# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/BRAMtoVGA/Nexys-4-Master.xdc

# Block Designs: bd/BRAMRW/BRAMRW.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAMRW || ORIG_REF_NAME==BRAMRW} -quiet] -quiet

# IP: bd/BRAMRW/ip/BRAMRW_blk_mem_gen_0_0/BRAMRW_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAMRW_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAMRW_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/clk25M/clk25M.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk25M || ORIG_REF_NAME==clk25M} -quiet] -quiet

# IP: bd/clk25M/ip/clk25M_clk_wiz_0_0/clk25M_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk25M_clk_wiz_0_0 || ORIG_REF_NAME==clk25M_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/BRAMRW/BRAMRW_ooc.xdc

# XDC: bd/clk25M/clk25M_ooc.xdc
